[package]
name = "wread-data-mongodb"
version = "0.1.0"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
mongodb="0.9.2"
bson="0.14.1"
serde = { version = "1.0.105", features = ["derive"] }
