[package]
name = "wread-data-mongodb"
version = "0.3.0"
authors = ["Saju Thankappan <sajuthankappan@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "read and write data for mongodb"
homepage = "https://github.com/sajuthankappan/wread-data-mongodb-rs"
repository = "https://github.com/sajuthankappan/wread-data-mongodb-rs"
readme = "README.md"
keywords = ["mongodb"]
categories = ["database"]

[dependencies]
log = "0.4.8"
mongodb="0.9.2"
bson="0.14.1"
serde = { version = "1.0.105", features = ["derive"] }
